# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'Mezzo-1.0' do
	pod "RMDateSelectionViewController", "~> 2.0.1"
    pod 'DatePickerCell'
    
    pod 'FBSDKCoreKit', '~> 4.4'
	pod 'Parse'
    pod 'ParseUI'
    pod 'ConvenienceKit'
	pod 'Mixpanel'
end

target 'Mezzo-1.0Tests' do
    pod 'FBSDKCoreKit', '~> 4.4'
	pod 'Parse'
    pod 'ConvenienceKit'
    pod 'ParseUI'
end

