# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Mezzo-1.0' do
	use_frameworks!
#	pod 'RealmSwift'
	platform :ios, '8.0'
	pod "RMDateSelectionViewController", "~> 2.0.1"
    pod 'FBSDKCoreKit', '~> 4.4'
	pod 'Parse'
    pod 'ParseUI'
    pod 'ConvenienceKit'
	pod 'Bond', '~> 3.7'
	pod 'Mixpanel'
end

target 'Mezzo-1.0Tests' do
	use_frameworks!
#	pod 'RealmSwift'
	platform :ios, '8.0'
    pod 'FBSDKCoreKit', '~> 4.4'
	pod 'Parse'
    pod 'ConvenienceKit'
    pod 'ParseUI'
end

